name: euses
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=2.4.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - json-c=0.13.1
  - numpy=1.19.1
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - pip=20.2.2
  - xlrd=1.2.0
  - pip:
    - affine==2.3.0
    - appdirs==1.4.4
    - attrs==19.3.0
    - backcall==0.2.0
    - beautifulsoup4==4.9.1
    - bottleneck==1.3.2
    - calliope==0.6.5
    - cftime==1.2.1
    - chardet==3.0.4
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cycler==0.10.0
    - decorator==4.4.2
    - descartes==1.1.0
    - fiona==1.8.13.post1
    - geographiclib==1.50
    # - geokit==git+https://github.com/ENSYSTRA/geokit.git
    - geopandas==0.8.1
    - geopy==2.0.0
    # - glaes==git+https://github.com/ENSYSTRA/glaes.git
    - idna==2.10
    - importlib-metadata==1.7.0
    - ipykernel==5.3.4
    - ipython==7.17.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.0a1
    - joblib==0.16.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.6
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - libpysal==4.3.0
    - markupsafe==2.0.0a1
    - matplotlib==3.3.1
    - munch==2.5.0
    - natsort==7.0.1
    - nbformat==5.0.7
    - netcdf4==1.5.4
    - networkx==2.4
    - nose==1.3.7
    - numexpr==2.7.1
    - ortools==7.8.7959
    - pandas==0.25.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - plotly==3.10.0
    - ply==3.11
    - prompt-toolkit==3.0.6
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyomo==5.6.9
    - pyparsing==2.4.7
    - pyproj==2.6.1.post1
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyutilib==5.8.0
    - pyzmq==19.0.2
    - rasterio==1.1.5
    - rasterstats==0.15.0
    - requests==2.24.0
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - shapely==1.7.0
    - simplejson==3.17.2
    - six==1.15.0
    - smopy==0.0.7
    - snuggs==1.4.7
    - soupsieve==2.0.1
    # - spopt==0.1.0
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - traitlets==5.0.0b1
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - xarray==0.14.1
    - zipp==3.1.0
