name: euses-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - calliope=0.6.6-post1
  - gdal=2.4.1

  - pip:
    - spopt==0.1.0
    - datapackage==1.15.1
    - numpy==1.19.1
    - openpyxl==3.0.6
    - rasterio==1.1.5
    - rasterstats==0.15.0
    - geopy==2.0.0
    - matplotlib==3.4.1
    - ipython
    - xlrd
    - jupyter
