name: euses-neos
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - calliope=0.6.7
  - gdal=2.4.1
  - mapclassify=2.4.0
  - coincbc=2.10.3
  - seaborn=0.11.2
  - pip:
    - spopt==0.1.0
    - datapackage==1.15.1
    - numpy==1.19.1
    - openpyxl==3.0.6
    - rasterio==1.1.5
    - rasterstats==0.15.0
    - geopy==2.0.0
    - matplotlib==3.4.3
    - h5netcdf==0.11.0
    - ipython==7.29.0
    - xlrd==2.0.1
    - jupyter==1.0.0
